### PR TITLE
Fixes #508 - Adding tax class causes error

### LINKED ISSUE #508: Tax Classes Page Error
When visiting the page Legacy -> Locations/Taxes -> Tax Classes the page loads as normal but will log the following error:

PHP Notice:  DateTime:  () cannot be formatted to Y-m-d H:i:s in /home/somewebsite/public_html/2point4/includes/OSC/OM/DateTime.php on line 52

### PR DESCRIPTION
**Pull request by scottcwilson**
Adding didn't set the update timestamp, so when the display attempted to render that it failed.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Sorry, the first version of this PR was messed up.  Fixed now.

**Comment by haraldpdl** [comment]
Hi Scott! Thanks for looking into this! Could you actually revert those changes and do the following instead:

```
        if (isset($tcInfo->last_modified)) {
          $contents[] = array('text' => OSCOM::getDef('text_info_last_modified') . ' ' . DateTime::toShort($tcInfo->last_modified));
        }
```

That can then be merged in. Thanks!

**Comment by scottcwilson** [comment]
Done.

**Comment by scottcwilson** [comment]
I must be going cross-eyed.  Thought I had fixed that!  OK done.

**Pull request merged**
